### ISSUE TITLE
공동구매 기능 이슈

### ISSUE THREAD

**Issue by dispear** [SW-Pettory/pettory#2]
# 기능
- [x] 1. 공동구매모임 전체 리스트 조회(검색, 정렬)
- [x] 2. 즐겨찾기 등록 및 해제
- [x] 3. 사용자가 등록한 즐겨찾기 조회
- [x] 4. 공동구매모임 특정 모임 상세 조회
- [x] 5. 공동구매모임 관리
    - [x] 5-1. insert 구현 (JPA)
    - [x] 5-2. update 구현 (JPA)
    - [x] 5-3. delete 구현  (JPA)
    - [x] 5-4 상태 관련 API ( 마감으로 자동 상태 변경, 현재 사용자 인원 수, 방장만 방 수정 가능, )
- [x] 6. 모임 참가
- [x] 7. 모임 나가기
- [x] 8. 모임 강퇴
    - [x] 8-1.강퇴된 사용자는 모임에 다시 못들어오는 기능
- [x] 9-1. 현재 공동구매모임의 전체 사용자 목록 조회
- [x] 9-2. 현재 사용자가 참여한 공동구매모임 목록 조회
~~10. 알림 기능(간단하게 표시만)~~
- [x] 11. 카테고리 관리
    - [x] 11-1. insert 구현 (JPA)
    - [x] 11-2. update 구현 (JPA)
    - [x] 11-3. delete 구현  (JPA)
- [x] 12. 공동구매 참가 
- [x] 13. 공동구매 참가 취소
- [x] 14. 공동구매 참가 마감(자동)
- [x] 15. 공동구매 참가자 리스트 조회(물품 수령 여부 등 확인)
- [x] 16. 공동구매 물품 배송 정보 등록(참가자, 방장)
~~17. 공동구매 물품 배송 정보 조회(참가자, 방장) -> 특정모임 상세 조회에서 받아오기 가능~~
- [x] 18. 공동구매 물품 수령 여부 변경
- [x] 19. 지급이력 확인 및 지급

## 주말에 집중적으로 할것
- 서비스 테스트 리스트 작성
- 엔티티끼리의 관계 설정 이후 서비스 기능 상세화(조건 적용)
- 결제 api 조사, 구현

**Comment by aosskfdlrla** [comment]
화이팅!

**Comment by dispear** [comment]
엔티티끼리 관계를 맺는 과정에서 쿼리와 레포 수정 가능성 높음
